FROM php:7.3.6-fpm-alpine3.9

RUN apk add --no-cache openssl composer mysql-client shadow
RUN docker-php-ext-install pdo pdo_mysql

WORKDIR /var/www
RUN rm -rf /var/www/html

COPY . /var/www

RUN composer install && \
        php artisan config:cache && \
        chmod -R 777 storage

RUN ln -s public html
RUN ln -s /var/www /usr/share/nginx

RUN usermod -u 1000 www-data
USER www-data

EXPOSE 9000
ENTRYPOINT ["./k8s/app/entrypoint.sh"]
