apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-redis
spec:
  replicas: 1

  selector: # usado pelo service
    matchLabels:
      app: laravel-redis
  
  template:
    metadata:
      labels: 
        app: laravel-redis
        role: master
    spec:
      containers:
        - image: redis
          name: laravel-redis-master
          ports:
            - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: laravel-redis-service
  labels: 
    app: laravel-redis-service
    role: master
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: laravel-redis
    role: master
