apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-mysql
spec:
  replicas: 1

  selector: # usado pelo service
    matchLabels:
      app: laravel-mysql
      tier: db

  template:
    metadata:
      labels:
        app: laravel-mysql
        tier: db
    spec:
      containers:
        - image: mysql:5.7
          name: laravel-mysql
          args:
            - "--ignore-db-dir=lost+found"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: laravel-mysql-secret
                  key: password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: laravel-mysql-persistent-storage
              mountPath: /var/lib/mysql

      volumes:
        - name: laravel-mysql-persistent-storage
          persistentVolumeClaim:
            claimName: laravel-mysql-volume-claim

