apiVersion: v1
kind: Secret
metadata:
  name: laravel-mysql-secret
type: Opaque
data:
  password: MTIzNDU2 #123456
  # echo 123456 | base64
  # MTIzNDU2Cg== is decoded as 123456\n
  # The right encoding should be MTIzNDU2 for 123456.
  # Please let me know if this is the case.
  # echo -n 123456 | base64

